<a href="https://colab.research.google.com/github/Jolanta27/numpy_exercises/blob/master/numpy_rozgrzewka.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. Utwórz trójwymiarową tablicę z jedynkami na przekątnej i zerami w innych miejscach

In [ ]:
import numpy as np
array = np.array([[1, 0, 0], [0, 1, 0], [0, 0, 1]])
print(array)

I = np.eye(3)
print(I)

[[1 0 0]
 [0 1 0]
 [0 0 1]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


2. Utwórz tablicę liczb 3x2 wypełnioną jedynkami.

In [ ]:
import numpy as np
array = np.array([[1, 1], [1, 1], [1, 1]])
print(array)

ones_array = np.ones((3, 2))
print(ones_array)

[[1 1]
 [1 1]
 [1 1]]
[[1. 1.]
 [1. 1.]
 [1. 1.]]


3. Utwórz macierz o kształcie 2x5, wypełnioną szóstkami.


In [ ]:
import numpy as np
matrix = np.full((2, 5), 6)
print(matrix)

[[6 6 6 6 6]
 [6 6 6 6 6]]


4. Create an array of 5, 13, 21, 29, ..., 101

In [ ]:
import numpy as np
array = np.arange(5, 102, 8)
print(array)

[  5  13  21  29  37  45  53  61  69  77  85  93 101]


5. Utwórz tablicę 1-D składającą się z 20 równomiernie rozmieszczonych elementów w przedziale od 7. do 12. włącznie.

In [ ]:
import numpy as np
array = np.linspace(7, 12, 20)
print(array)

[ 7.          7.26315789  7.52631579  7.78947368  8.05263158  8.31578947
  8.57894737  8.84210526  9.10526316  9.36842105  9.63157895  9.89473684
 10.15789474 10.42105263 10.68421053 10.94736842 11.21052632 11.47368421
 11.73684211 12.        ]


6. Utwórz dwuwymiarową tablicę (4x4), której przekątna jest równa [1, 2, 3, 4] i zawiera 0 w innych miejscach

In [ ]:
import numpy as np
array = np.diag([1, 2, 3, 4])
print(array)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


7. Niech x będzie macierzą o następujących wymiarach [10, 10, 3] i niech wszystkie jej elementy będą równe jeden. Następnie przekształć x tak, aby tworzył macierz (2Darray), a rozmiar drugiego wymiaru był równy 150.

In [ ]:
import numpy as np
x = np.ones((10, 10, 3))
x_reshaped = np.reshape(x, (-1 ,150))
print(x_reshaped)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1.]]


8.Niech x będzie tablicą [[1, 2, 3], [4, 5, 6]]. Przekształć ją na [1 4 2 5 3 6]

In [ ]:
import numpy as np
array = np.array([[1,2,3], [4,5,6]])
changed_array = np.ravel(array, order='F')
print(changed_array)

[1 4 2 5 3 6]


9.Niech X = np.arange(1, 5).reshape((2, 2)) i oblicz wyznacznik X

In [ ]:
import numpy as np
x = np.arange(1, 5).reshape((2, 2))
print(x)
det_X = np.linalg.det(x)
print(det_X)

[[1 2]
 [3 4]]
-2.0000000000000004


10.Zwraca sumę wzdłuż przekątnej A = np.linspace(2, 16, 16).reshape(4, 4)

In [ ]:
A = np.linspace(2, 16, 16).reshape(4, 4)
sum_diag_A = np.trace(A)
print(sum_diag_A)

36.0


11.Znajdź odwrotność np.array([[1., 2.], [3., 4.]])

In [ ]:
import numpy as np
matrix = np.array([[1.,2.], [3.,4.]])
inverse_matrix = np.linalg.inv(matrix)
print(inverse_matrix)

[[-2.   1. ]
 [ 1.5 -0.5]]


12.Dla następujących wektorów,

x = np.array([4, 5, 6, 13])
y = np.array([5, 0, 6, 11])
sprawdź, które elementy x są większe od elementów y.

In [ ]:
import numpy as np
x = np.array([4, 5, 6, 13])
y = np.array([5, 0, 6, 11])
greater_elements = x > y
print(greater_elements)

[False  True False  True]
