<a href="https://colab.research.google.com/github/Jolanta27/numpy_exercises/blob/master/Time_to_Practice__Numpy_2_with_partial_solutions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<img height="180px" src="https://drive.google.com/uc?export=view&id=141XOz6N4nk8Ru1sAl7vOsAToCLrSFCAX" alt="SDA logo" align="left" hspace="30px" vspace="50px"/>

# Welcome to your next notebook with SDA!

During the classes we will mostly use [Google Colaboratory](https://colab.research.google.com/?hl=en) which is a free Jupyter notebook environment that requires no setup and runs entirely in the cloud.

However, for bigger projects, especially involving Deep Learning and/or big data reading, it might be a better choice to setup Jupyter Notebook or Jupyter Lab on your computer. Also, it is worth noticing that there is a great number of useful extensions (see [nbextensions](https://jupyter-contrib-nbextensions.readthedocs.io/en/latest/index.html) and [jupyter-labextension](https://jupyterlab.readthedocs.io/en/stable/user/extensions.html)) not available for Colab users.

<img src="https://drive.google.com/uc?export=view&id=1UO2urRciECzoKE_vHy4RMGfFbkOWOGlW" alt="SDA logo" align="left" width="100px" hspace="10px" vspace="10px"/>
<br>

# TASKS

<img src="https://drive.google.com/uc?export=view&id=141XOz6N4nk8Ru1sAl7vOsAToCLrSFCAX" alt="SDA logo" width="150" align='right'/>
<br>

## Linear Algebra

### Please make sure that **<font color='#306998'>TASKS </font><font color='#ffd33b'>1.1 - 1.10</font>** and **<font color='#306998'>TASKS </font><font color='#ffd33b'>1.10 - 1.24</font>** are already completed :)

### **<font color='#306998'>TASK </font><font color='#ffd33b'>1.25</font>**

For the matrix from task 1.7:
* calculate its determinant,
* find inverse matrix.

$$
A=
\begin{bmatrix}
1 & 2 & 3 & 4 \\
5 & 6 & 7 & 8 \\
9 & 10 & 11 & 12 \\
13 & 14 & 15 & 16
\end{bmatrix}
$$

In [ ]:
import numpy as np

In [ ]:
A = np.arange(1, 17).reshape(4, 4)
det_A = np.linalg.det(A)
print(f"Determinant of A:, {det_A}")

Determinant of A:, 0.0


In [48]:
try:
  inv_A = np.linalg.inv(A)
  print(f"Inverse of A: \n{inv_A}")
except np.linalg.LinAlgError:
  print("Matrix A is singular, it does not have an inverse.")


Inverse of A: 
[[-0.66666667  0.33333333]
 [-1.16666667  0.83333333]]


Next, change the last value to 0:

In [ ]:
B = A.copy()
B[-1, -1] = 0
# B.flat[-1] = 0

B

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15,  0]])

In [ ]:
np.linalg.det(B), np.linalg.inv(B)

(-2.273736754432328e-13,
 array([[-2.81474977e+14,  5.62949953e+14, -2.81474977e+14,
         -6.25000000e-02],
        [ 5.62949953e+14, -1.12589991e+15,  5.62949953e+14,
          6.25000000e-02],
        [-2.81474977e+14,  5.62949953e+14, -2.81474977e+14,
          6.25000000e-02],
        [-7.81250000e-02,  9.37500000e-02,  4.68750000e-02,
         -6.25000000e-02]]))

In [ ]:
np.matmul(B, np.linalg.inv(B))

array([[ 0.96875,  0.0625 ,  0.0625 ,  0.     ],
       [ 0.03125,  0.4375 ,  0.25   ,  0.     ],
       [-0.90625,  1.0625 ,  0.1875 ,  0.     ],
       [-0.59375,  0.1875 ,  0.125  ,  1.     ]])

In [ ]:
np.round(np.matmul(B, np.linalg.inv(B)), 5)

array([[ 0.96875,  0.0625 ,  0.0625 ,  0.     ],
       [ 0.03125,  0.4375 ,  0.25   ,  0.     ],
       [-0.90625,  1.0625 ,  0.1875 ,  0.     ],
       [-0.59375,  0.1875 ,  0.125  ,  1.     ]])

... and try with differnt matrix:

$$
C=
\begin{bmatrix}
3 & 2 & -1 & 1 \\
1 & 0 & 1 & 2 \\
2 & 1 & 1 & -1 \\
1 & 1 & 1 & 0
\end{bmatrix}
$$

In [ ]:
C = np.array([[3,2,-1,1], [1,0,1,2], [2,1,1,-1], [1,1,1,0]])
C

array([[ 3,  2, -1,  1],
       [ 1,  0,  1,  2],
       [ 2,  1,  1, -1],
       [ 1,  1,  1,  0]])

In [ ]:
np.round(np.matmul(C, np.linalg.inv(C)))

array([[ 1.,  0.,  0., -0.],
       [-0.,  1.,  0.,  0.],
       [-0.,  0.,  1.,  0.],
       [ 0.,  0., -0.,  1.]])

**<font color='#ed7d31'>SOLVING SYSTEMS OF LINEAR EQUATIONS</font>**

There are a few methods to solve systems of linear equations at a *school-level* mathematics. Although they are very effective they can require a lot of time and work, and can be especially difficult to apply to a larger number of variables. See, how you can address it with Linear Algebra.

Let's consider the following system of equations:
$$
\begin{cases}
    x_1 + x_2 = 4\\
    2x_1 - x_2 = 5
\end{cases}
$$
it can be written as $Ax = y,$ where
$$
x=\begin{bmatrix}
    x_1 \\
    x_2
\end{bmatrix},
y=\begin{bmatrix}
    y_1 \\
    y_2
\end{bmatrix}=
\begin{bmatrix}
    4 \\
    5
\end{bmatrix},
$$and
$$
A=\begin{bmatrix}
1 & 1\\
2 & -1
\end{bmatrix}.
$$
If an inverse matrix $A^{-1}$ exists, you can easily solve the equation by multiplying both sides by it from the left side:
$$
Ax=y \\
x=Ix=A^{-1} Ax=A^{-1} y
$$


### **<font color='#306998'>TASK </font><font color='#ffd33b'>1.26</font>**

Solve the system of equations mentioned above.

*Correct answer: $$x = (x_1, x_2) = (3, 1).$$*

*Hint: There are functioned defined within NumPy package for both of these tasks; matrix inverse & mathematical multiplication of two matrices.*

In [ ]:
A = np.array([[1, 1], [1, -1]])
y = np.array([4, 5])

In [ ]:
A_inv = np.linalg.inv(A)
A_inv

array([[ 0.5,  0.5],
       [ 0.5, -0.5]])

In [ ]:
x = np.dot(A_inv, y)
print(f"The solution is: x1 = {x[0]}, x2 = {x[1]}")

The solution is: x1 = 4.5, x2 = -0.5


The systems below were copied from: [Lumen: College Algebra](https://courses.lumenlearning.com/wmopen-collegealgebra/chapter/introduction-systems-of-linear-equations-three-variables/).

### **<font color='#306998'>TASK </font><font color='#ffd33b'>1.27</font>**

What is the solution to the system of equations below?
\begin{cases}
    x_1 - 2x_2+3x_3 = 9\\
    -x_1 +3x_2- x_3 = -6\\
    2x_1-5x_2+5x_3=17
\end{cases}

*Correct answer: $$x = (x_1, x_2, x_3) = (1, -1, 2).$$*

In [ ]:
import numpy as np
A = np.array([[1, -2, 3], [-1, 3, -1], [2, -5, 5]])
y = np.array([9, -6, 17])

x = np.linalg.solve(A, y)

print(f"The solution is: x1 = {x[0]}, x2 = {x[1]}, x3 = {x[2]}")

The solution is: x1 = 1.0, x2 = -1.0, x3 = 2.0


### **<font color='#306998'>TASK </font><font color='#ffd33b'>1.28</font>**

Solve the system of equations in three variables:
\begin{cases}
    2x_1 + x_2 - 2x_3 = -1\\
    3x_1 - 3x_2 - x_3 = 5\\
    x_1 - 2x_2 + 3x_3 = 6
\end{cases}

*Correct answer: $$x = (x_1, x_2, x_3) = (-2, 1, 1).$$*

In [ ]:
import numpy as np
A = np.array([[2, 1, -2], [3, -3, -1], [1, -2, 3]])
y = np.array([-1, 5, 6])

x = np.linalg.solve(A, y)
print(f"The solution is: x1: {x[0]}, x2: {x[1]}, x3: {x[2]}")

The solution is: x1: 1.0000000000000002, x2: -0.9999999999999997, x3: 1.0000000000000002


### **<font color='#306998'>TASK </font><font color='#ffd33b'>1.28</font>**

Determine whether the triple $x = (x_1, x_2, x_3) = (3, -2, 1)$ is a solution to the system:

\begin{cases}
    x_1 + x_2 + x_3 = 2\\
    6x_1 - 4x_2 + 5x_3 = 31\\
    5x_1 + 2x_2 + 2x_3 = 13.
\end{cases}

*Correct answer: yes, it is.*

In [ ]:
x1, x2, x3 = 3, -2, 1

eq1 = x1 + x2 + x3 == 2
eq2 = 6*x1 - 4*x2 + 5*x3 == 31
eq3 = 5*x1 + 2*x2 + 2*x3 == 13

solution = eq1 and eq2 and eq3
print(f"The triple (x1, x2, x3) = (3, -2, 1) is a solution to the system: {solution}")

The triple (x1, x2, x3) = (3, -2, 1) is a solution to the system: True


### **<font color='#306998'>TASK </font><font color='#ffd33b'>1.29</font>**

Check whether the system solution exists:

\begin{cases}
    x_1 - 3x_2 + x_3 = 4\\
    -x_1 + 2x_2 - 5x_3 = 3\\
    5x_1 - 13x_2 + 13x_3 = 8.
\end{cases}

*Correct answer: no, it does not.*

*Hint: matrix is not full-rank, i.e $rank(A) = 2 \neq 3.$*

In [ ]:
A = np.array([[1, -3, 1], [-1, 2, -5], [5, -13, 13]])
rank_A = np.linalg.matrix_rank(A)
solution_exists = rank_A == A.shape[1]
print(f"If the system solution exist: {solution_exists}")

If the system solution exist: False


### **<font color='#306998'>TASK </font><font color='#ffd33b'>1.30</font>** (optional)

Find eigenvalues and eigenvectors associated with them for the following matrices:
* $
A_1=\begin{bmatrix}
-5 & 2\\
-7 & 4
\end{bmatrix}
$

* $
A_2=\begin{bmatrix}
1 & 0\\
0 & -3
\end{bmatrix}
$

* $
A_3=\begin{bmatrix}
5 & -10 & -5\\
2 & 14 & 2\\
-4 & -8 & 6
\end{bmatrix}
$

* $
A_4=\begin{bmatrix}
1 & -1 & 2\\
1 & 0 & -1\\
1 & 1 & 2
\end{bmatrix}
$

Solutions can be complex numbers, $z\in\mathbb{C}$, as for $A_4$.

In [ ]:
A = np.array([[-5, 2], [-7, 4]])
eigvals_A1, eigvecs_A1 = np.linalg.eig(A)
A2 = np.array([[1, 0], [0, -3]])
eigvals_A2, eigvecs_A2 = np.linalg.eig(A2)
A3 = np.array([[5, -10, -5], [2, 14, 2], [-4, -8, 6]])
eigvals_A3, eigvecs_A3 = np.linalg.eig(A3)
A4 = np.array([[1, -1, 2], [1, 0, -1], [1, 1, 2]])
eigvals_A4, eigvecs_A4 = np.linalg.eig(A4)
print(f"For A1, the eigenvalues are {eigvals_A1} and the corresponding eigenvectors are {eigvecs_A1}")
print(f"For A2, the eigenvalues are {eigvals_A2} and the corresponding eigenvectors are {eigvecs_A2}")
print(f"For A3, the eigenvalues are {eigvals_A3} and the corresponding eigenvectors are {eigvecs_A3}")
print(f"For A4, the eigenvalues are {eigvals_A4} and the corresponding eigenvectors are {eigvecs_A4}")


For A1, the eigenvalues are [-3.  2.] and the corresponding eigenvectors are [[-0.70710678 -0.27472113]
 [-0.70710678 -0.96152395]]
For A2, the eigenvalues are [ 1. -3.] and the corresponding eigenvectors are [[1. 0.]
 [0. 1.]]
For A3, the eigenvalues are [ 5. 10. 10.] and the corresponding eigenvectors are [[ 7.45355992e-01  7.44760246e-16 -5.22799043e-01]
 [-2.98142397e-01 -4.47213595e-01  5.75730417e-01]
 [ 5.96284794e-01  8.94427191e-01 -6.28661791e-01]]
For A4, the eigenvalues are [3.00000000e+00+0.j         1.38777878e-16+1.41421356j
 1.38777878e-16-1.41421356j] and the corresponding eigenvectors are [[-7.07106781e-01+0.j         -6.28694613e-02+0.62237591j
  -6.28694613e-02-0.62237591j]
 [-3.76172481e-19+0.j          6.91564075e-01+0.j
   6.91564075e-01-0.j        ]
 [-7.07106781e-01+0.j         -6.28694613e-02-0.35564338j
  -6.28694613e-02+0.35564338j]]


<img src="https://drive.google.com/uc?export=view&id=141XOz6N4nk8Ru1sAl7vOsAToCLrSFCAX" alt="SDA logo" width="150" align='right'/>
<br>

## Appendix: random numbers generators

1. Randomly generated number(s) from normal (Gauss) distribution.
```python
np.random.normal()
np.random.normal(size=6)
```
1. Randomly selected numbers from the uniform system.
```python
np.random.uniform(size=6)
```
1. Randomly selected number from a specific range.
```python
np.random.randint(3, 30, size=6)
```
1. Randomly selected floating-point number
```python
np.random.random()
```