<a href="https://colab.research.google.com/github/Jolanta27/numpy_exercises/blob/master/Time_to_Practice__Numpy_0_with_partial_solutions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<img height="180px" src="https://drive.google.com/uc?export=view&id=141XOz6N4nk8Ru1sAl7vOsAToCLrSFCAX" alt="SDA logo" align="left" hspace="30px" vspace="50px"/>

# Welcome to your next notebook with SDA!

During the classes we will mostly use [Google Colaboratory](https://colab.research.google.com/?hl=en) which is a free Jupyter notebook environment that requires no setup and runs entirely in the cloud.

However, for bigger projects, especially involving Deep Learning and/or big data reading, it might be a better choice to setup Jupyter Notebook or Jupyter Lab on your computer. Also, it is worth noticing that there is a great number of useful extensions (see [nbextensions](https://jupyter-contrib-nbextensions.readthedocs.io/en/latest/index.html) and [jupyter-labextension](https://jupyterlab.readthedocs.io/en/stable/user/extensions.html)) not available for Colab users.

<img src="https://drive.google.com/uc?export=view&id=1UO2urRciECzoKE_vHy4RMGfFbkOWOGlW" alt="SDA logo" align="left" width="100px" hspace="10px" vspace="10px"/>
<br>

# TASKS

<img src="https://drive.google.com/uc?export=view&id=141XOz6N4nk8Ru1sAl7vOsAToCLrSFCAX" alt="SDA logo" width="150" align='right'/>
<br>

## Linear Algebra

### **<font color='#306998'>TASK </font><font color='#ffd33b'>1.1</font>**

1. Create a NumPy array with consecutive values from 1 to 9. Display and then invert this array (first element becomes last, etc.).
1. Do the same for the numbers between 7 and 19 (including these numbers).

1a/

In [ ]:
import numpy as np

In [ ]:
naturals_1_9 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
print(naturals_1_9)

[1 2 3 4 5 6 7 8 9]


In [ ]:
inverted_array = naturals_1_9[::-1]
print(inverted_array)

[9 8 7 6 5 4 3 2 1]


In [ ]:
np.arange(1, 10)  # start is inclusive, right exclusive (aka right-open)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.linspace(1, 9, 9)  # both inclusive

array([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [ ]:
naturals_7_19 = np.arange(7, 20)
print(naturals_7_19)

[ 7  8  9 10 11 12 13 14 15 16 17 18 19]


In [ ]:
inverted_7_19 = naturals_7_19[::-1]
print(inverted_7_19)

[19 18 17 16 15 14 13 12 11 10  9  8  7]


In [ ]:
np.array([i for i in range(1, 10)])  # with list comprehension and range function

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

1b/

In [ ]:
naturals_1_9[::-1]  # start:stop:step

array([9, 8, 7, 6, 5, 4, 3, 2, 1])

In [ ]:
# using numpy function flip
np.flip(naturals_1_9)

array([9, 8, 7, 6, 5, 4, 3, 2, 1])

In [ ]:
# list comprehension
np.array([naturals_1_9[i] for i in range(len(naturals_1_9) - 1, -1, -1)])

array([9, 8, 7, 6, 5, 4, 3, 2, 1])

In [ ]:
# with a for loop
inverted_naturals = []
for i in range(len(naturals_1_9) - 1, -1, -1):
    inverted_naturals.append(naturals_1_9[i])
np.array(inverted_naturals)

array([9, 8, 7, 6, 5, 4, 3, 2, 1])

In [ ]:
# using Python function sorted
np.array(
    sorted(naturals_1_9, reverse=True)
)

array([9, 8, 7, 6, 5, 4, 3, 2, 1])

2/

In [ ]:
naturals_7_19 = np.arange(7, 20)
print(naturals_7_19)

[ 7  8  9 10 11 12 13 14 15 16 17 18 19]


In [ ]:
inverted_7_19 = naturals_7_19[::-1]
print(inverted_7_19)

[19 18 17 16 15 14 13 12 11 10  9  8  7]


### **<font color='#306998'>TASK </font><font color='#ffd33b'>1.2</font>**

1. Create the following NumPy array: `np.array([1, 23, 4, 31, 1, 1, 4, 23, 4, 1])`; and then list all unique (non-repeating) elements.
1. Perform similar task with the following NumPy array np.array([44, 1, 7, 12, 7, 44, 4, 7, 12, 1]) and then for each unique value, print out the value itself and the number of its occurences.

1/

In [ ]:
my_array = np.array([1, 23, 4, 31, 1, 1, 4, 23, 4, 1])

unique_elements = []

for elem in my_array:
    if elem not in unique_elements:
        unique_elements.append(elem)

unique_elements

[1, 23, 4, 31]

In [ ]:
# built-in numpy function
np.unique(my_array)

array([ 1,  4, 23, 31])

In [ ]:
# using set to extract unique elements
set(my_array)

{1, 4, 23, 31}

2/

In [ ]:
my_array_2 = np.array([44, 1, 7, 12, 7, 44, 4, 7, 12, 1])
print(my_array_2)
unique_values, counts = np.unique(my_array_2, return_counts=True)
print(unique_values)
for value, count in zip(unique_values, counts):
  print(f"Value: {value}, Count: {count}")

[44  1  7 12  7 44  4  7 12  1]
[ 1  4  7 12 44]
Value: 1, Count: 2
Value: 4, Count: 1
Value: 7, Count: 3
Value: 12, Count: 2
Value: 44, Count: 2


*Tip for the second part of the task:*

*If you want to additionally count the occurrences of each of the unique elements then you can:*

*   use `np.unique()` function with `return_count=True`
*   use `from collections import Counter`, read more https://docs.python.org/3/library/collections.html#collections.Counter
*   use a dict with a for loop to `+1` each time an element shows up


### **<font color='#306998'>TASK </font><font color='#ffd33b'>1.3</font>**

1. Create a 3x3 matrix (by using `reshape` method) containign values ranging from 2 to 10 (inclusively).
1. Next, construct a 2x5 matrix filled with consecutive integers beginning at 35 and concluding at 44.
  * Explore additional configurations that this matrix can have (different shapes).


1/

In [ ]:
np.array([[2, 3, 4], [5, 6, 7], [8, 9, 10]])

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [ ]:
np.array([
    [2, 3, 4],
    [5, 6, 7],
    [8, 9, 10]
])

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [ ]:
np.arange(2, 11).reshape(3, 3)  # 3 rows, 3 columns

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [ ]:
np.arange(2, 11).reshape(3, -1)  # 3 rows, automatically count the number of columns

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [ ]:
np.arange(2, 11).reshape(-1, 3)  # 3 columns, automatically count the number of rows

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

2/

In [ ]:
array = np.arange(35, 45)
print(array)
matrix_2x5 = array.reshape(2, 5)
print(matrix_2x5)
matrix_2x5 = array.reshape(5, 2)
print(matrix_2x5)
matrix_2x5 = array.reshape(10, 1)
print(matrix_2x5)

[35 36 37 38 39 40 41 42 43 44]
[[35 36 37 38 39]
 [40 41 42 43 44]]
[[35 36]
 [37 38]
 [39 40]
 [41 42]
 [43 44]]
[[35]
 [36]
 [37]
 [38]
 [39]
 [40]
 [41]
 [42]
 [43]
 [44]]


### **<font color='#306998'>TASK </font><font color='#ffd33b'>1.4</font>**

1. Create an array with six random integers between 10 and 30.
1. Create an array with eight random integers between 102 and 159.
1. Create an array with ten random real values between 0 and 7. (optional)

1/ See Appendix for more information

In [ ]:
np.random.randint(10, 31, size=6)

array([10, 13, 21, 24, 21, 25])

In [ ]:
np.random.choice(
    np.arange(10, 31),  # values to choose from
    size=6,  # number of values to choose
    replace=True  # non-unique elements, possible repetitions
)

array([10, 30, 21, 17, 13, 11])

2/

In [ ]:
np.random.randint(102, 160, size=8)

array([126, 125, 147, 155, 105, 145, 158, 141])

In [ ]:
array = np.random.uniform(0, 7, 10)
print(array)

[0.04996959 3.18441306 5.58003716 3.21689875 5.60892004 5.00493648
 5.78657519 4.45416873 6.20832943 3.4338994 ]


### **<font color='#306998'>TASK </font><font color='#ffd33b'>1.5</font>**

1. Use the following code to define 2D array, ie. matrix, and then determine its dimension and number of elements.
1. Perform the same operations using matrices from 1.3.

```
A = np.array([[1, 2, 3, 4], [5, 6, -7, 1]])
```

1/

In [ ]:
A = np.array([[1, 2, 3, 4], [5, 6, -7, 1]])

In [ ]:
dimensions = A.shape
dimensions

(2, 4)

In [ ]:
rows, columns = dimensions

In [ ]:
A.size

8

2/

In [ ]:
import numpy as np

B = np.array([[2, 3, 4], [5, 6, 7], [8, 9, 10]])
print(B)
dimensions = B.shape
print(dimensions)
num_elements = B.size
print(num_elements)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]
(3, 3)
9


In [ ]:
array = np.arange(35, 45)
print(array)
dimenstions = array.shape
print(dimenstions)
num_elem = array.size
print(num_elem)

[35 36 37 38 39 40 41 42 43 44]
(10,)
10


### **<font color='#306998'>TASK </font><font color='#ffd33b'>1.6</font>**

1/ From the array of values: `[23, 45, 112, 150, 43, 254, 95, 8]` filter for those that are greater than 100.

In [ ]:
array = np.array([23, 45, 112, 150, 43, 254, 95, 8])

In [ ]:
array > 100  # boolean mask

array([False, False,  True,  True, False,  True, False, False])

In [ ]:
array[array > 100]  # indexing

array([112, 150, 254])

In [ ]:
# less efficient
array_above_100 = []

for i in array:
    if i > 100:
        array_above_100.append(i)

array_above_100

[112, 150, 254]

In [ ]:
[i for i in array if i > 100]

[112, 150, 254]

In [ ]:
# useful if you need a list of indices
np.where(array > 100)[0]

array([2, 3, 5])

2/ From the array `[10, 21, 32, 43, 54, 65, 76, 87]`, filter for those values that are odd.

In [ ]:
np.array([10, 21, 32, 43, 54, 65, 76, 87])
mask = array % 2 !=0
odd_values = array[mask]
print(odd_values)

[35 37 39 41 43]


### **<font color='#306998'>TASK </font><font color='#ffd33b'>1.7</font>**

Create the 4x4 matrix below, then:
* display the item from the second row and the third column,

$$
A=
\begin{bmatrix}
1 & 2 & 3 & 4 \\
5 & 6 & 7 & 8 \\
9 & 10 & 11 & 12 \\
13 & 14 & 15 & 16
\end{bmatrix}
$$

In [ ]:
A = np.arange(1, 17).reshape(4, 4)
A[:,3]

array([ 4,  8, 12, 16])

### **<font color='#306998'>TASK </font><font color='#ffd33b'>1.8</font>**

Print out all natural numbers less than 100 that are divisible by 11. Try not to use any iteration over loop.

In [ ]:
array = np.arange(11,100,11)
print(array)

[11 22 33 44 55 66 77 88 99]


### **<font color='#306998'>TASK </font><font color='#ffd33b'>1.9</font>**

Create a vector consisting of consecutive natural numbers: `6, 7, 8, ..., 35`. Change its shape in several ways.

In [ ]:
vector = np.arange(6, 36)
print(vector)
matrix_2x15 = vector.reshape(2,15)
print(matrix_2x15)
matrix_3x10 = vector.reshape(3, 10)
print(matrix_3x10)
matrix_5x6 = vector.reshape(5, 6)
print(matrix_5x6)

[ 6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29
 30 31 32 33 34 35]
[[ 6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27 28 29 30 31 32 33 34 35]]
[[ 6  7  8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23 24 25]
 [26 27 28 29 30 31 32 33 34 35]]
[[ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]


### **<font color='#306998'>TASK </font><font color='#ffd33b'>1.10</font>**

Using `np.reshape()` method, create a `3x3` matrix with all integers from 51 to 59.

In [ ]:
array = np.arange(51, 60)
print(array)
matrix_3x3 = array.reshape(3, 3)
print(matrix_3x3)

[51 52 53 54 55 56 57 58 59]
[[51 52 53]
 [54 55 56]
 [57 58 59]]


<img src="https://drive.google.com/uc?export=view&id=141XOz6N4nk8Ru1sAl7vOsAToCLrSFCAX" alt="SDA logo" width="150" align='right'/>
<br>

## Appendix: random numbers generators

1. Randomly generated number(s) from normal (Gauss) distribution.
```python
np.random.normal()
np.random.normal(size=6)
```
1. Randomly selected numbers from the uniform system.
```python
np.random.uniform(size=6)
```
1. Randomly selected number from a specific range.
```python
np.random.randint(3, 30, size=6)
```
1. Randomly selected floating-point number
```python
np.random.random()
```